### ISSUE TITLE
Code is not available?

### ISSUE THREAD

**Issue by YJ-He** [Z-Zheng/ChangeOS#2]
Dear author, I'm interested in this project, but cannot see any codes as you mentioned in the paper. Could you fix it sometime?

**Comment by Z-Zheng** [comment]
Please check out https://github.com/Z-Zheng/ChangeOS#getting-started.
The code is [here](https://github.com/Z-Zheng/ChangeOS/blob/master/changeos/__init__.py).
Only APIs are available now, so I make it as tiny as possible.

**Comment by YJ-He** [comment]
@Z-Zheng Thanks for your prompt reply, found it already. Its place is really out of my thoughts, thank you anyway.
